# Generated by Django 3.1.5 on 2021-02-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
